apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: {{ .Values.image.spring }}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring
spec:
  selector:
    app: spring
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP


